# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Find change poins in data vector
#'
#' @param x numeric vector
#' @return numeric vector of ids
#' @export
ChangePoints <- function(x) {
    .Call('pvar_ChangePoints_fromR', PACKAGE = 'pvar', x)
}

#' Find p-variation
#' 
#' @param x numeric vector
#' @param p numeric vector
#' @param LSI numeric vector
#' @return list...
#' @export
pvarC <- function(x, p, LSI = 3L) {
    .Call('pvar_pvarC', PACKAGE = 'pvar', x, p, LSI)
}

#' Add pvars
#' 
#' @param PV1 numeric vector
#' @param PV2 numeric vector
#' @param AddIfPossible numeric vector
#' @return list...
#' @export
AddPvarC <- function(PV1, PV2, AddIfPossible = TRUE) {
    .Call('pvar_AddPvar', PACKAGE = 'pvar', PV1, PV2, AddIfPossible)
}

CheckSmallIntervals <- function(x, p, dn) {
    .Call('pvar_test_CheckSmallIntervals', PACKAGE = 'pvar', x, p, dn)
}

prepare_prt <- function(x, p) {
    .Call('pvar_test_prepare_prt', PACKAGE = 'pvar', x, p)
}

